#! /bin/bash
echo " "
echo "Preparing the Workstation to Run this lab"
echo " "
echo "Note: This command script should be run with 'source start' "
echo "to prepare the active terminal session. "
echo " "

echo "Activating Python Virtual Environment"
source venv/bin/activate
echo "Opening Incognito browser windows for lab"
#killall Google\ Chrome
open -na "Google Chrome" --args -incognito "https://172.31.37.61" "https://ciscolive-workspace.slack.com/?redir=%2Fmessages%2FCDMS29EKX%2F"

echo " "
