#! /bin/bash
echo " "
echo "Preparing the Workstation to Run this lab"
echo " "
echo "Note: This command script should be run with 'source start' "
echo "to prepare the active terminal session. "
echo " "

echo "Activating Python Virtual Environment"
source venv/bin/activate

echo " "
